Repository AY2122S2-CS2113T-T09-3/tp, pull requests merged in 2022-03, with the labels that each got.

#20 Branch command parser
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Doctor.java
  src/main/java/seedu/duke/assets/Patient.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#29 Wei li add and delete patient feature
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Patient.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#37 Branch add medicine
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Medicine.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/assets/Person.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#38 Refactor parseAddPatient method
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#43 Add description for addPatient input format errors, save new Patient to patientList object. Add description for deletePatient input format errors, add exception and change to 1-indexing
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#45 Branch delete medicine
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/test/java/seedu/duke/helper/CommandTest.java
  src/test/java/seedu/duke/helper/ParserTest.java
Labels: priority.High

#48 View patient update
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
Labels: type.Story, priority.High

#49 Add doctor
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
Labels: type.Story, priority.High

#51 Implemented 3 methods in UI.
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/helper/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Low

#46 delete doctor and view doctor
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Doctor.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
Labels: type.Story, type.Task, priority.High

#47 Branch storage
  .gitignore
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Doctor.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/Medicine.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/assets/Patient.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/assets/Person.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#52 Final fixes
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/UI.java
Labels: type.Task, priority.High

#54 create basic readme
  docs/README.md
Labels: type.Task, priority.Medium

#75 Branch update user guide
  docs/UserGuide.md
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#72 Branch update print statements
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/assets/Doctor.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/assets/Patient.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#78 Updated Developer Guide Skeleton
  docs/DeveloperGuide.md
Labels: priority.High

#76 Implement basic Appointment and AppointmentList
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Appointment.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/UI.java
Labels: type.Task, priority.High

#80 Exception and validator abstraction
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/exception/HalpmiException.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
  src/main/java/seedu/duke/helper/Validator.java
  src/test/java/seedu/duke/assets/MedicineListTest.java
  src/test/java/seedu/duke/helper/ParserTest.java
Labels: type.Enhancement, priority.High

#82 Add UI print methods to new Appt and ApptList code
  src/main/java/seedu/duke/assets/Appointment.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/UI.java
Labels: type.Task, priority.High

#86 For DG Draft. To add in code for find appt also.
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/helper/Command.java
  src/main/java/seedu/duke/helper/Parser.java
Labels: type.Task, priority.High

#94 Dg parser validation
  docs/DeveloperGuide.md
  docs/Diagrams/Parser.puml
  src/main/java/seedu/duke/Duke.java
Labels: type.Task, priority.Low

#95 Branch junit
  src/main/java/seedu/duke/exception/DuplicateEntryException.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Validator.java
  src/main/java/seedu/duke/helper/command/Command.java
  src/test/java/seedu/duke/helper/ParserTest.java
  src/test/java/seedu/duke/helper/command/AddDoctorCommandTest.java
  src/test/java/seedu/duke/helper/command/AddMedicineCommandTest.java
  src/test/java/seedu/duke/helper/command/AddPatientCommandTest.java
  src/test/java/seedu/duke/helper/command/DeleteDoctorCommandTest.java
  src/test/java/seedu/duke/helper/command/DeleteMedicineCommandTest.java
  src/test/java/seedu/duke/helper/command/DeletePatientCommandTest.java
  src/test/java/seedu/duke/helper/command/EditMedicineCommandTest.java
Labels: priority.Medium

#96 Integrating previous appt code into the current codebase
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Appointment.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/Validator.java
  src/main/java/seedu/duke/helper/command/AddAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/Command.java
  src/main/java/seedu/duke/helper/command/ViewAppointmentCommand.java
  src/main/java/seedu/duke/status/Status.java
Labels: type.Task, priority.High

#104 Add some JUnit and Assertions
  build.gradle
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/Storage.java
  src/test/java/seedu/duke/assets/AppointmentListTest.java
  src/test/java/seedu/duke/assets/PatientListTest.java
  src/test/java/seedu/duke/helper/ParserTest.java
  src/test/java/seedu/duke/helper/command/ViewAppointmentCommandTest.java
Labels: type.Task, priority.High

#111 Wei li appt code find and view
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/Validator.java
  src/main/java/seedu/duke/helper/command/Command.java
  src/main/java/seedu/duke/helper/command/ViewAppointmentCommand.java
  src/main/java/seedu/duke/status/Status.java
  src/test/java/seedu/duke/assets/AppointmentListTest.java
  src/test/java/seedu/duke/helper/command/ViewAppointmentCommandTest.java
Labels: type.Task, priority.High

#108 Branch user guide
  docs/README.md
  docs/UserGuide.md
Labels: priority.High

#113 Fixes downcasting for FinderCommand classes
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/List.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/command/FindDoctorCommand.java
  src/main/java/seedu/duke/helper/command/FindMedicineCommand.java
  src/main/java/seedu/duke/helper/command/FindPatientCommand.java
  src/main/java/seedu/duke/status/Status.java
Labels: type.Enhancement, priority.Medium, severity.Low

#114 Wei li delete appt
  docs/UserGuide.md
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/command/DeleteAppointmentCommand.java
Labels: type.Task, priority.High

#118 Branch edit appointment
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
  src/main/java/seedu/duke/helper/Validator.java
  src/main/java/seedu/duke/helper/command/EditAppointmentCommand.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#117 Update view method exception
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/List.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/command/ViewAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/ViewDoctorCommand.java
  src/main/java/seedu/duke/helper/command/ViewMedicineCommand.java
  src/main/java/seedu/duke/helper/command/ViewPatientCommand.java
  src/test/java/seedu/duke/helper/command/ViewAppointmentCommandTest.java
Labels: priority.Medium

#121 Edit changes
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/CommandLineTable.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/UI.java
  src/test/java/seedu/duke/helper/ParserTest.java
Labels: type.Task, priority.High

#122 Refactor view appt
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Validator.java
  src/main/java/seedu/duke/helper/command/FindAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/UpdateMedicineInventoryCommand.java
  src/main/java/seedu/duke/helper/command/ViewAppointmentCommand.java
  src/main/java/seedu/duke/helper/finder/AppointmentFinder.java
Labels: type.Task, priority.High

#125 Branch dg architecture
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/OverallArch.png
  docs/diagrams/SequenceDiagram.png
  docs/diagrams/SequenceDiagram.puml
  docs/diagrams/StorageClassUML.png
  docs/diagrams/StorageClassUML.puml
Labels: priority.High

#132 Add UML for Med and Appt classes
  docs/DeveloperGuide.md
  docs/diagrams/AppointmentListUML.png
  docs/diagrams/AppointmentListUML.puml
  docs/diagrams/AppointmentUML.png
  docs/diagrams/AppointmentUML.puml
  docs/diagrams/MedicineListUML.png
  docs/diagrams/MedicineListUML.puml
  docs/diagrams/MedicineUML.png
  docs/diagrams/MedicineUML.puml
  src/main/java/seedu/duke/assets/Medicine.java
Labels: type.Task, priority.High

#135 Correcting Format Issues present in DG
  docs/DeveloperGuide.md
  docs/diagrams/ParserClassUML.png
  docs/diagrams/ParserUML.png
  docs/diagrams/ValidatorClassUML.png
  docs/diagrams/ValidatorUML.png
Labels: type.Task, priority.High
