Repository AY2122S2-CS2113T-T09-3/tp, pull requests merged in 2022-04, with the labels that each got.

#178 Implement IdGenerator and changing add appt cmd
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentListUML.png
  docs/diagrams/AppointmentListUML.puml
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Appointment.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/IdGenerator.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/Validator.java
  src/main/java/seedu/duke/helper/command/AddAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/CheckIfDoctorExistsCommand.java
  src/main/java/seedu/duke/helper/command/CheckIfPatientExistsCommand.java
  src/main/java/seedu/duke/helper/command/Command.java
Labels: type.Enhancement, priority.High

#182 Updated help feature in UI v3
  docs/UserGuide.md
  docs/diagrams/CommandClassUML.png
  docs/diagrams/CommandClassUML.puml
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/UI.java
  src/main/java/seedu/duke/helper/Validator.java
Labels: type.Task, priority.Medium, severity.Low

#184 Create my draft PPP
  docs/team/johndoe.md
  docs/team/tanweili.md
Labels: priority.Low

#183 Dispense Medicine Feature
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/Appointment.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/ExpiryComparator.java
  src/main/java/seedu/duke/assets/Medicine.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/helper/Parser.java
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/Validator.java
  src/main/java/seedu/duke/helper/command/CheckForMedicineStockCommand.java
  src/main/java/seedu/duke/helper/command/CheckIfAppointmentTodayCommand.java
  src/main/java/seedu/duke/helper/command/DispenseMedicineCommand.java
  src/main/java/seedu/duke/status/Status.java
Labels: type.Story, priority.High

#186 Wei li minor updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentListUML.png
  docs/diagrams/AppointmentListUML.puml
  docs/diagrams/AppointmentUML.png
  docs/diagrams/AppointmentUML.puml
  docs/diagrams/Doctor.png
  docs/diagrams/Doctor.puml
  docs/diagrams/DoctorList.png
  docs/diagrams/DoctorList.puml
  docs/diagrams/ExceptionClass.png
  docs/diagrams/ExceptionClass.puml
  docs/diagrams/ManagerClass.png
  docs/diagrams/ManagerClass.puml
  docs/diagrams/MedicineListUML.png
  docs/diagrams/MedicineListUML.puml
  docs/diagrams/MedicineUML.png
  docs/diagrams/MedicineUML.puml
  docs/diagrams/ParserClassUML.png
  docs/diagrams/ParserClassUML.puml
  docs/diagrams/Patient.png
  docs/diagrams/Patient.puml
  docs/diagrams/PatientList.png
  docs/diagrams/PatientList.puml
  docs/diagrams/StorageClassUML.png
  docs/diagrams/StorageClassUML.puml
  docs/diagrams/UIClass.puml
  docs/diagrams/UIClassUML.png
  docs/diagrams/ValidatorClassUML.png
  docs/diagrams/ValidatorClassUML.puml
  docs/team/tanweili.md
  src/main/java/seedu/duke/helper/Validator.java
  src/test/java/seedu/duke/assets/AppointmentListTest.java
Labels: type.Task, priority.High

#185 Update appointment results
  docs/UserGuide.md
  docs/team/Anvitha-r.md
  docs/team/kktai1512.md
  docs/team/wraineflores.md
  src/main/java/seedu/duke/assets/Appointment.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/helper/UI.java
  src/main/java/seedu/duke/helper/Validator.java
Labels: type.Enhancement, priority.Low, severity.Low

#187 Branch docs update sharif
  docs/DeveloperGuide.md
  docs/team/shxr3f.md
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/helper/command/AddAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/AddDoctorCommand.java
  src/main/java/seedu/duke/helper/command/AddMedicineCommand.java
  src/main/java/seedu/duke/helper/command/AddPatientCommand.java
  src/main/java/seedu/duke/helper/command/CheckForMedicineStockCommand.java
  src/main/java/seedu/duke/helper/command/CheckIfAppointmentTodayCommand.java
  src/main/java/seedu/duke/helper/command/Command.java
  src/main/java/seedu/duke/helper/command/DeleteAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/DeleteDoctorCommand.java
  src/main/java/seedu/duke/helper/command/DeleteMedicineCommand.java
  src/main/java/seedu/duke/helper/command/DeletePatientCommand.java
  src/main/java/seedu/duke/helper/command/DispenseMedicineCommand.java
  src/main/java/seedu/duke/helper/command/EditAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/EditDoctorCommand.java
  src/main/java/seedu/duke/helper/command/EditMedicineCommand.java
  src/main/java/seedu/duke/helper/command/EditPatientCommand.java
  src/main/java/seedu/duke/helper/command/FindAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/FindDoctorCommand.java
  src/main/java/seedu/duke/helper/command/FindMedicineCommand.java
  src/main/java/seedu/duke/helper/command/FindPatientCommand.java
  src/main/java/seedu/duke/helper/command/UpdateMedicineInventoryCommand.java
  src/main/java/seedu/duke/helper/command/ViewAppointmentCommand.java
  src/main/java/seedu/duke/helper/command/ViewDoctorCommand.java
  src/main/java/seedu/duke/helper/command/ViewMedicineCommand.java
  src/main/java/seedu/duke/helper/command/ViewPatientCommand.java
  src/main/java/seedu/duke/status/Status.java
Labels: priority.Medium

#192 Update my PPP
  docs/team/tanweili.md
Labels: type.Task, priority.Medium

#194 Wei li updates2
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/ViewAppointmentImplementation.puml
  docs/diagrams/ViewAppointmentImplementationUML.png
  docs/photos/tanweili.jpg
  docs/team/tanweili.md
Labels: type.Task, priority.High

#193 Code review
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DispenseMed.png
  docs/diagrams/DispenseMed.puml
  docs/diagrams/SequenceDiagram.png
  docs/diagrams/SequenceDiagram.puml
  docs/diagrams/StorageClassUML.png
  docs/diagrams/StorageClassUML.puml
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/MedicineList.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#198 Make user stories table nicer
  docs/DeveloperGuide.md
  docs/team/tanweili.md
Labels: priority.High, severity.Medium

#199 Add line break to properly display user stories table
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, severity.Low

#201 Update UG to change from admission date to registration date
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/Validator.java
  src/main/java/seedu/duke/helper/command/FindPatientCommand.java
Labels: type.Bug, priority.High

#205 Update appt and apptList UML images to reflect new methods
  docs/diagrams/AppointmentListUML.png
  docs/diagrams/AppointmentListUML.puml
  docs/diagrams/AppointmentUML.png
  docs/diagrams/AppointmentUML.puml
  docs/diagrams/DoctorList.png
  docs/diagrams/DoctorList.puml
  docs/diagrams/ManagerClass.png
  docs/diagrams/Patient.png
  docs/diagrams/Patient.puml
  docs/diagrams/PatientList.png
  docs/diagrams/PatientList.puml
Labels: type.Bug, priority.High

#207 Fix appointment bugs
  docs/AboutUs.md
  docs/photos/sharif.jpg
  src/main/java/seedu/duke/Manager.java
  src/main/java/seedu/duke/assets/AppointmentList.java
  src/main/java/seedu/duke/assets/Doctor.java
  src/main/java/seedu/duke/assets/DoctorList.java
  src/main/java/seedu/duke/assets/Patient.java
  src/main/java/seedu/duke/assets/PatientList.java
  src/main/java/seedu/duke/helper/UI.java
  src/main/java/seedu/duke/helper/command/DeleteAppointmentCommand.java
Labels: type.Bug

#208 Fixing issue with loading data of older date
  src/main/java/seedu/duke/helper/Storage.java
  src/main/java/seedu/duke/helper/Validator.java
Labels: type.Bug

#212 Change DOA to DOR in UG
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Low
